#!/bin/bash
sudo apt-get install bash-completion mlocate leafpad nano ttf-ubuntu-font-family mate-desktop-environment-core lightdm lightdm-gtk-greeter synaptic software-properties-common python-software-properties
